// Placeholder Firebase options for each flavor and platform.
// Replace values with those generated by `flutterfire configure` for each environment.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

import 'package:app/core/app/app_flavor.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions byFlavorAndPlatform(AppFlavor flavor) {
    if (kIsWeb) {
      return switch (flavor) {
        AppFlavor.prod => webProd,
        AppFlavor.stg => webStg,
        AppFlavor.dev => webDev,
      };
    }

    final platform = defaultTargetPlatform;
    switch (platform) {
      case TargetPlatform.android:
        return switch (flavor) {
          AppFlavor.prod => androidProd,
          AppFlavor.stg => androidStg,
          AppFlavor.dev => androidDev,
        };
      case TargetPlatform.iOS:
        return switch (flavor) {
          AppFlavor.prod => iosProd,
          AppFlavor.stg => iosStg,
          AppFlavor.dev => iosDev,
        };
      case TargetPlatform.macOS:
        return switch (flavor) {
          AppFlavor.prod => macosProd,
          AppFlavor.stg => macosStg,
          AppFlavor.dev => macosDev,
        };
      case TargetPlatform.windows:
        return switch (flavor) {
          AppFlavor.prod => windowsProd,
          AppFlavor.stg => windowsStg,
          AppFlavor.dev => windowsDev,
        };
      case TargetPlatform.linux:
        return switch (flavor) {
          AppFlavor.prod => linuxProd,
          AppFlavor.stg => linuxStg,
          AppFlavor.dev => linuxDev,
        };
      case TargetPlatform.fuchsia:
        throw UnsupportedError('Fuchsia is not supported.');
    }
  }

  // DEV
  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_WEB_API_KEY',
    appId: 'YOUR_DEV_WEB_APP_ID',
    messagingSenderId: 'YOUR_DEV_WEB_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    authDomain: 'YOUR_DEV_WEB_AUTH_DOMAIN',
    storageBucket: 'YOUR_DEV_BUCKET',
    measurementId: 'YOUR_DEV_MEASUREMENT_ID',
  );
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_ANDROID_API_KEY',
    appId: 'YOUR_DEV_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_DEV_ANDROID_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_BUCKET',
  );
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_IOS_API_KEY',
    appId: 'YOUR_DEV_IOS_APP_ID',
    messagingSenderId: 'YOUR_DEV_IOS_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_BUCKET',
    iosBundleId: 'app.dev.bundle',
  );
  static const FirebaseOptions macosDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_MACOS_API_KEY',
    appId: 'YOUR_DEV_MACOS_APP_ID',
    messagingSenderId: 'YOUR_DEV_MACOS_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_BUCKET',
    iosBundleId: 'app.dev.macos',
  );
  static const FirebaseOptions windowsDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_WINDOWS_API_KEY',
    appId: 'YOUR_DEV_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_DEV_WINDOWS_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_BUCKET',
  );
  static const FirebaseOptions linuxDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_LINUX_API_KEY',
    appId: 'YOUR_DEV_LINUX_APP_ID',
    messagingSenderId: 'YOUR_DEV_LINUX_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_BUCKET',
  );

  // STG
  static const FirebaseOptions webStg = FirebaseOptions(
    apiKey: 'YOUR_STG_WEB_API_KEY',
    appId: 'YOUR_STG_WEB_APP_ID',
    messagingSenderId: 'YOUR_STG_WEB_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    authDomain: 'YOUR_STG_WEB_AUTH_DOMAIN',
    storageBucket: 'YOUR_STG_BUCKET',
    measurementId: 'YOUR_STG_MEASUREMENT_ID',
  );
  static const FirebaseOptions androidStg = FirebaseOptions(
    apiKey: 'YOUR_STG_ANDROID_API_KEY',
    appId: 'YOUR_STG_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_STG_ANDROID_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    storageBucket: 'YOUR_STG_BUCKET',
  );
  static const FirebaseOptions iosStg = FirebaseOptions(
    apiKey: 'YOUR_STG_IOS_API_KEY',
    appId: 'YOUR_STG_IOS_APP_ID',
    messagingSenderId: 'YOUR_STG_IOS_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    storageBucket: 'YOUR_STG_BUCKET',
    iosBundleId: 'app.stg.bundle',
  );
  static const FirebaseOptions macosStg = FirebaseOptions(
    apiKey: 'YOUR_STG_MACOS_API_KEY',
    appId: 'YOUR_STG_MACOS_APP_ID',
    messagingSenderId: 'YOUR_STG_MACOS_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    storageBucket: 'YOUR_STG_BUCKET',
    iosBundleId: 'app.stg.macos',
  );
  static const FirebaseOptions windowsStg = FirebaseOptions(
    apiKey: 'YOUR_STG_WINDOWS_API_KEY',
    appId: 'YOUR_STG_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_STG_WINDOWS_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    storageBucket: 'YOUR_STG_BUCKET',
  );
  static const FirebaseOptions linuxStg = FirebaseOptions(
    apiKey: 'YOUR_STG_LINUX_API_KEY',
    appId: 'YOUR_STG_LINUX_APP_ID',
    messagingSenderId: 'YOUR_STG_LINUX_SENDER_ID',
    projectId: 'YOUR_STG_PROJECT_ID',
    storageBucket: 'YOUR_STG_BUCKET',
  );

  // PROD
  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_WEB_API_KEY',
    appId: 'YOUR_PROD_WEB_APP_ID',
    messagingSenderId: 'YOUR_PROD_WEB_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    authDomain: 'YOUR_PROD_WEB_AUTH_DOMAIN',
    storageBucket: 'YOUR_PROD_BUCKET',
    measurementId: 'YOUR_PROD_MEASUREMENT_ID',
  );
  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_ANDROID_API_KEY',
    appId: 'YOUR_PROD_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_PROD_ANDROID_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_BUCKET',
  );
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_IOS_API_KEY',
    appId: 'YOUR_PROD_IOS_APP_ID',
    messagingSenderId: 'YOUR_PROD_IOS_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_BUCKET',
    iosBundleId: 'app.prod.bundle',
  );
  static const FirebaseOptions macosProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_MACOS_API_KEY',
    appId: 'YOUR_PROD_MACOS_APP_ID',
    messagingSenderId: 'YOUR_PROD_MACOS_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_BUCKET',
    iosBundleId: 'app.prod.macos',
  );
  static const FirebaseOptions windowsProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_WINDOWS_API_KEY',
    appId: 'YOUR_PROD_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_PROD_WINDOWS_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_BUCKET',
  );
  static const FirebaseOptions linuxProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_LINUX_API_KEY',
    appId: 'YOUR_PROD_LINUX_APP_ID',
    messagingSenderId: 'YOUR_PROD_LINUX_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_BUCKET',
  );
}
