arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
use-escaped-strings: true
