arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-localization-file: generated_hanko_localizations.dart
output-class: GeneratedHankoLocalizations
nullable-getter: false
