name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  clock: ^1.1.2
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  fake_async: ^1.3.3
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2
  intl: ^0.20.2
  logging: ^1.3.0
  riverpod: ^3.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
