version: '3'

vars:
  DEFAULT_ENV: dev

tasks:
  deps:
    cmds:
      - make deps
  fmt:
    cmds:
      - make fmt
  fmt-check:
    cmds:
      - make fmt-check
  test-integration:
    cmds:
      - make test-integration
  test-ci:
    cmds:
      - make test-ci
  cover:
    cmds:
      - make cover
  docker-build:
    cmds:
      - make docker-build
  docker-run:
    cmds:
      - make docker-run
  lint:
    cmds:
      - make lint
  test:
    cmds:
      - make test
  run:
    cmds:
      - make run
  build:
    cmds:
      - make build
  tidy:
    cmds:
      - make tidy
  vuln:
    cmds:
      - make vuln
  generate:
    cmds:
      - make generate
